travis:
  secure:
    BINSTAR_TOKEN: KD232jo4E7Nxf3GBgNlSfKqTbd9t8nAXQiiKjww9cS1qjvT74BlfolGX1+LM56OPUdkC3LJ141uTsJp+kQwaJ0py8R1tkMw0byyZwFqcHoPtF2MPqjVJABvnWkNUbPHGagfyoKh/vK9qhkUryC3FUFdgCAPk0hjCetOT3mh3kC1BvOWcwdQkn3MIZRhAhbRC8D/ePT05NcXq1xrkVhZ9Lw+gSmunlGChbmr1CZrFz/EyAWrzfz3snzf1xjZZO+wfu6yB2zKWTE0/vm5k4x63vpeevo1Ccy92swd/JTN+yvHcGmhW82EOXtpJfEip+KEjWP1h7JReMYjdAa5/4y3J6u3XhsqcYC5kY5t8aA9+dGspig3Tl5ubI9eFQQLbRBZkWUqAH9DXkj9Y1OPFUaiOkeIctZJlbB1J82KaIDhSuj5viAk4hqoLXoW41aJsiJyDvqSLblveUn944eAd2pU9y24I05pEsYPfqb1uBc69kAdAV7gAp69W62CWQQE+2PuYRVtagyD1FXSf02NqRNnxts0rJEV0T31KmMjNgi3ub/EIKMVNhMmDjEzySQfHw19hslkf5iKzOi64zE3bLOmsWqT/Wfsny4H+X4D34C+96NFn+/DQgPiN8ouY3k/Tos2drpa0V9MWmA95Yd6p0DAReeO01xR+5mxA8oRTXbvQm4I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
